version: '3'
services:
    apache:
        build: .docker/apache
        container_name: dnd_apache
        ports:
          - 80:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/wwwroot/dnd
        depends_on:
          - php

    mysql:
        ports:
          - 3306:3306
        image: mysql
        command: "--default-authentication-plugin=mysql_native_password"
        container_name: dnd_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dnd
            MYSQL_USER: dnd
            MYSQL_PASSWORD: dnd

    php:
        build: .docker/php
        container_name: dnd_php
        volumes:
          - .:/home/wwwroot/dnd
        environment:
          - maildev_host=dnd_maildev
        depends_on:
          - maildev
          - mysql
        links:
          - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: dnd_phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 8080:80
        links:
            - mysql

    maildev:
        image: djfarrelly/maildev
        container_name: dnd_maildev
        ports:
          - 8001:80
